// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package watcher

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WatcherServiceClient is the client API for WatcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatcherServiceClient interface {
	GetLastChange(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Change, error)
	StreamChanges(ctx context.Context, in *Empty, opts ...grpc.CallOption) (WatcherService_StreamChangesClient, error)
}

type watcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatcherServiceClient(cc grpc.ClientConnInterface) WatcherServiceClient {
	return &watcherServiceClient{cc}
}

func (c *watcherServiceClient) GetLastChange(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Change, error) {
	out := new(Change)
	err := c.cc.Invoke(ctx, "/watcher.WatcherService/GetLastChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watcherServiceClient) StreamChanges(ctx context.Context, in *Empty, opts ...grpc.CallOption) (WatcherService_StreamChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &WatcherService_ServiceDesc.Streams[0], "/watcher.WatcherService/StreamChanges", opts...)
	if err != nil {
		return nil, err
	}
	x := &watcherServiceStreamChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WatcherService_StreamChangesClient interface {
	Recv() (*Change, error)
	grpc.ClientStream
}

type watcherServiceStreamChangesClient struct {
	grpc.ClientStream
}

func (x *watcherServiceStreamChangesClient) Recv() (*Change, error) {
	m := new(Change)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WatcherServiceServer is the server API for WatcherService service.
// All implementations must embed UnimplementedWatcherServiceServer
// for forward compatibility
type WatcherServiceServer interface {
	GetLastChange(context.Context, *Empty) (*Change, error)
	StreamChanges(*Empty, WatcherService_StreamChangesServer) error
	mustEmbedUnimplementedWatcherServiceServer()
}

// UnimplementedWatcherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWatcherServiceServer struct {
}

func (UnimplementedWatcherServiceServer) GetLastChange(context.Context, *Empty) (*Change, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastChange not implemented")
}
func (UnimplementedWatcherServiceServer) StreamChanges(*Empty, WatcherService_StreamChangesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamChanges not implemented")
}
func (UnimplementedWatcherServiceServer) mustEmbedUnimplementedWatcherServiceServer() {}

// UnsafeWatcherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatcherServiceServer will
// result in compilation errors.
type UnsafeWatcherServiceServer interface {
	mustEmbedUnimplementedWatcherServiceServer()
}

func RegisterWatcherServiceServer(s grpc.ServiceRegistrar, srv WatcherServiceServer) {
	s.RegisterService(&WatcherService_ServiceDesc, srv)
}

func _WatcherService_GetLastChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherServiceServer).GetLastChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watcher.WatcherService/GetLastChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherServiceServer).GetLastChange(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatcherService_StreamChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WatcherServiceServer).StreamChanges(m, &watcherServiceStreamChangesServer{stream})
}

type WatcherService_StreamChangesServer interface {
	Send(*Change) error
	grpc.ServerStream
}

type watcherServiceStreamChangesServer struct {
	grpc.ServerStream
}

func (x *watcherServiceStreamChangesServer) Send(m *Change) error {
	return x.ServerStream.SendMsg(m)
}

// WatcherService_ServiceDesc is the grpc.ServiceDesc for WatcherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatcherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "watcher.WatcherService",
	HandlerType: (*WatcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastChange",
			Handler:    _WatcherService_GetLastChange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChanges",
			Handler:       _WatcherService_StreamChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/watcher/watcher.proto",
}
